version: "3"

services:
  node:
    image: deipdev/testnet:node_a2aa3b6f
    restart: on-failure
    ports:
    - "8090:8090"
    - "2001:2001"
    expose:
    - "8090"
    - "2001"
    env_file:
    - config/node.env
  full_node:
    image: deipdev/testnet:fullnode_a2aa3b6f
    restart: on-failure
    ports:
    - "8090:8090"
    - "2001:2001"
    expose:
    - "8090"
    - "2001"
    env_file:
    - config/fullnode.env
  wallet:
    image: deipdev/testnet:wallet_a2aa3b6f
    restart: on-failure
    volumes:
    - ./data:/var/lib/wallet
    command: ["-s", "ws://82.196.2.5:8090", "-w", "/var/lib/wallet/wallet.json"]
    stdin_open: true
    tty: true