version: "3"

services:
  node:
    image: deipdev/testnet:node_latest
    restart: on-failure
    ports:
    - "8090:8090"
    - "2001:2001"
    expose:
    - "8090"
    - "2001"
    env_file:
    - node-config.env
    volumes:
    - ./data:/var/lib/deipd
  full_node:
    image: deipdev/testnet:fullnode_latest
    restart: on-failure
    ports:
    - "8090:8090"
    - "2001:2001"
    expose:
    - "8090"
    - "2001"
    env_file:
    - fullnode-config.env
    volumes:
    - ./data:/var/lib/deipd
  wallet:
    image: deipdev/testnet:wallet_latest
    restart: on-failure
    volumes:
    - ./data:/var/lib/wallet